### ISSUE TITLE
Request: a page explaining and showing types support in CL

### ISSUE THREAD

**Issue by vindarel** [LispCookbook/cl-cookbook#104]
As someone curious about CL, I heard that one can compile a form and be notified at compile time of type errors. So CL has types ? How that ? How do they compare to Python or to Haskell ? Because we are in a cookbook I'd like many code samples.

As a practicing learner, I saw `declare` and sometimes `the`. I'd like a quick reference. I'd like to see how Slime will warn me, and if and when it is useful.

- declare CLHS: http://www.lispworks.com/documentation/lw51/LWRM/html/lwref-75.htm

a first search:
- great article: http://blog.30dor.com/2014/03/21/performance-and-types-in-lisp/
- two or three nice little examples: https://news.ycombinator.com/item?id=1154069
- CL the language: https://www.cs.cmu.edu/Groups/AI/html/cltl/clm/node103.html#SECTION001300000000000000000
- https://softwareengineering.stackexchange.com/questions/187316/types-in-lisp-and-scheme
- https://www.common-lisp.net/project/cmucl/doc/cmu-user/compiler-hint.html ?
- paper of the python CMU compiler with examples: http://sci-hub.cc/10.1145/141478.141558

**Comment by vindarel** [comment]
Reference this:

https://medium.com/@MartinCracauer/static-type-checking-in-the-programmable-programming-language-lisp-79bb79eb068a

```
(defun meh (p1)
  (declare (fixnum p1))
  (+ p1 3))
(defun meh2 (p1)
  (declare (fixnum p1))
  (+ p1 "8"))

Gets you this:

2 compiler notes:typecheck-demo.lisp:7:3:

  note: deleting unreachable code

  warning:

    Constant "8" conflicts with its asserted type NUMBER.

    See also:

      SBCL Manual, Handling of Types [:node]Compilation failed.
```

**Comment by Ambrevar** [comment]
And this: https://alhassy.github.io/TypedLisp/
By the way, this issue title mentions SLIME, but I think this is unrelated, this comes from compiler support.

SBCL might have the most extensive support for compile-time type checking, but it seems that CCL and ECL at least support some of it too.

It would be nice to highlight that the lack of static typing in Lisp is mostly a misconception.  And it would be even nicer to make those features more obvious to beginners :)

The correct term here seems to be not "static typing" but "gradual typing".

Finally, none of the examples show that you can type the return value of a function as well:

```lisp
(declaim (ftype (function (fixnum) fixnum) add))
(defun add (n)
	(+ n  1))
```

**Comment by arademaker** [comment]
Maybe you can also make the case about the effect of this declaration:

```
CL-USER> (defun add1 (n)
	   (+ n  1))
ADD1
CL-USER> (disassemble #'add1)
; disassembly for ADD1
; Size: 35 bytes. Origin: #x227A0FE4                          ; ADD1
; 0FE4:       498B5D10         MOV RBX, [R13+16]              ; thread.binding-stack-pointer
; 0FE8:       48895DF8         MOV [RBP-8], RBX
; 0FEC:       BF02000000       MOV EDI, 2
; 0FF1:       488BD6           MOV RDX, RSI
; 0FF4:       FF1425A800B021   CALL QWORD PTR [#x21B000A8]    ; GENERIC-+
; 0FFB:       488B75F0         MOV RSI, [RBP-16]
; 0FFF:       488BE5           MOV RSP, RBP
; 1002:       F8               CLC
; 1003:       5D               POP RBP
; 1004:       C3               RET
; 1005:       CC10             BREAK 16                       ; Invalid argument count trap
```

versus 

```
CL-USER> (declaim (ftype (function (fixnum) fixnum) add))
                     (defun add (n) (+ n  1))
ADD
CL-USER> (disassemble #'add)
; disassembly for ADD
; Size: 45 bytes. Origin: #x227A108D                          ; ADD
; 8D:       498B4510         MOV RAX, [R13+16]                ; thread.binding-stack-pointer
; 91:       488945F8         MOV [RBP-8], RAX
; 95:       488D4301         LEA RAX, [RBX+1]
; 99:       488BD0           MOV RDX, RAX
; 9C:       48D1E2           SHL RDX, 1
; 9F:       7014             JO L0
; A1:       488BD0           MOV RDX, RAX
; A4:       48D1E2           SHL RDX, 1
; A7:       480F4015A1FFFFFF CMOVO RDX, [RIP-95]              ; 4611686018427387904
; AF:       488BE5           MOV RSP, RBP
; B2:       F8               CLC
; B3:       5D               POP RBP
; B4:       C3               RET
; B5: L0:   CC48             BREAK 72                         ; OBJECT-NOT-FIXNUM-ERROR
; B7:       02               BYTE #X02                        ; RAX
; B8:       CC10             BREAK 16                         ; Invalid argument count trap
```

**Comment by vindarel** [comment]
feedback: https://www.reddit.com/r/lisp/comments/dos0hq/compiletime_type_checking_for_variables_and/



This:

    (declaim (ftype (function () string) bad-adder))
    (defun bad-adder ()
           (let ((res 10))
             (loop for name in  *all-names*
                do (incf res name))
             (format nil "finally doing sth with ~a" res)))


when *all-names* is a list-of-strings, doesn't throw a warning at compilation.

This throws:

    (defun bad-adder ()
           (let ((res 10))
             (loop for name in  *all-names*
                return (incf res name))))
=> type warning

and using the:

                do (incf res (the string name)))

=> type warning

It's like type checking only works at boundaries: with parameters, functions input and output, but not inside functions.

**Comment by Ambrevar** [comment]
It works inside functions too, not just at the boundaries.
Consider  this:

--8<---------------cut here---------------start------------->8---
(defparameter *non-fixnum* "foo")
(defparameter *fixnum* 17)

(defun foo (n)
  (let ((x (+ n 1)))
    (1+ *fixnum*)
    (1+ *non-fixnum*)
    x))

(foo 100)
--8<---------------cut here---------------end--------------->8---

You'll get an error for `*non-fixnum*` but not for `*fixnum*`.

It seems that SBCL does not perform type checking for complex types,
e.g. types involving `satisfies`.
