### ISSUE TITLE
Possibly use examples from SO' documentation (shutting down)

### ISSUE THREAD

**Issue by vindarel** [LispCookbook/cl-cookbook#108]
https://stackoverflow.com/documentation/common-lisp/topics

now on https://web.archive.org/web/20170803161434/https://stackoverflow.com/documentation/common-lisp/topics

**Comment by pnathan** [comment]
Seems like a good idea to me!

**Comment by pnathan** [comment]
@vindarel I should be able to vacuum these topics down in the next week or so. 

What do you think about a general "FAQ" section to put these into?

**Comment by vindarel** [comment]
hey what, you mean every topic of SO in the FAQ ? There are Macros, ASDF, loop… they belong to their corresponding page, don't they ? If they don't have one already, why not. 

But also, don't feel obliged to import every one of them: it's possible that a lot are irrelevant for the Cookbook. Some are too short and need a lot of rework, others are outdated (buildapp) or already tackled (types of lists, unit testing…). 

ps: also there's a Misc page, not sure of its purpose and relevance either
