### ISSUE TITLE
Clarifying Using Emacs with Common Lisp Page

### ISSUE THREAD

**Issue by artforlife** [LispCookbook/cl-cookbook#116]
While going through the part of cookbook that is related on using Emacs and Common Lisp, I noticed that the code snippets lack clarity about how they should be run. Should they be run in the SLIME buffer or the regular LISP buffer? If the latter is the case, a lot of key shortcuts do not work. 

This is the page in question: http://lispcookbook.github.io/cl-cookbook/emacs-ide.html

**Comment by vindarel** [comment]
Hello, thanks for looking into this. Lately I cleaned this up (removed a lot of cruft) but I didn't check all examples. They're mean to be written in a buffer which has Slime mode activated (not in the REPL). Feel free to rephrase what's needed for better clarity.

Maybe such a highly precise TOC isn't really needed (8 bullets in "Editing") where a quick list of commands and the reference to the packages' documentation can be enough for getting started.

Also I'd love some animated gifs :)

**Comment by artforlife** [comment]
I'll clarify some of those things that confused me. What GIFs do you have in mind? For running the commands?

On another note, are you looking to add anything with Hunchentoot? There is a [solid tutorial](http://adamtornhill.com/articles/lispweb.htm) which is slightly outdated, but can be brought up-to-date (I have been going through it successfully). It would probably be prudent to mention that Clack, Woo, Caveman2 are better alternatives.

Lastly, I am suggesting we start a section in the Cookbook along [these](http://borretti.me/article/common-lisp-sotu-2015) lines. I am relatively new to the community, so I cannot be sure about the state of all entries on the list.

**Comment by vindarel** [comment]
let's not bother about gifs just yet :)

Indeed, I'd like the cookbook to have a web development section. We have an issue about that: #105 (if you plan do heavily use this tutorial, don't forget to ask the author) We would mention Clack & co indeed (Clack isn't an alternative since it uses Hunchentoot by default. Caveman is a framework.).

This "State of CL 2015" is a great reference indeed ! It's still recent so you can be pretty sure I guess :) Otherwise you can check out:

- http://lisp-lang.org/wiki/article/recommended-libraries by the same F. Borreti
- https://github.com/CodyReichert/awesome-cl with even more stuff (but some older)

**Comment by Ambrevar** [comment]
I think too the Emacs / SLIME page deservers a big update.
Don't spend to much time on the obvious / not-so-important stuff.

Spend more time on the gems:
- slime-who-*
- slime-eval-last-expression-in-repl (C-c C-j)
- slime-list-compiler-notes
- slime-export-symbol-at-point (C-c x)
- slime-export-class
- slime-trace-dialog-toggle-trace (C-c M-t)
- slime-inspect-definition
- slime-delete-system-fasls (useful when fasls are out-of-sync)
- slime-repl-clear-buffer (C-c M-o: useful when lispy/paredit goes berserk)
- slime-profile-package, then run the desired functions, then
  slime-profile-report.
- hyperspec-lookup-format and hyperspec-lookup-reader-macro


In particular with `slime-who-specializes`, it lists the methods of a class, which answers a common complaint around people common from the Algol family: they miss the ability to complete the methods of the `foo` class when typing `foo.<TAB>`.

**Comment by vindarel** [comment]
improvements done, but can still be better

80ae07ed0498c991c3dc1497bafbc6302664afc5
62cfdcafa337525e14d214da954b3514553a7ef8
c82aef793e16a13f0be9d45faa8aef1d4ffe183b
db6cc2e7bd29ed08b3fafac5fa06896bbde4800a
etc
