### ISSUE TITLE
[index.md] broken - all links reference .html files

### ISSUE THREAD

**Issue by rprimus** [LispCookbook/cl-cookbook#133]
Sat Dec 23 15:08:50 GMT 2017

```index.md```:  All links point to (non-existent) files with ```.html``` extensions.
These should have ```.md``` extensions.

A simple ```s/.html$/.md/g``` should fix it.

**Comment by rprimus** [comment]
Sat Dec 23 15:39:54 GMT 2017

Also fix references to ```windows.html``` and ```emacs-ide.html```.

**Comment by pnathan** [comment]
Interestingly, when examining the live site here - http://lispcookbook.github.io/cl-cookbook/editor-support.html the links work. The fact that the links point to html but the files are .md is an artifact of the rendering system, I believe. Can you explain the discrepancy otherwise?

**Comment by rprimus** [comment]
Sat Dec 23 19:14:16 GMT 2017

Hi @pnathan - noticed some problems when looking at ```emacs-ide.md``` - the ```s*.lisp``` files were not showing.

After fixing my ruby installation ([homebrew issue 22012](https://github.com/Homebrew/homebrew-core/issues/22012)) ,  ran ```jeckyll serve``` and saw that the site was now referencing the ```.md``` files and thus broken.

Will retract the pull request and close this issue.
