### ISSUE TITLE
How to set proxy [from sourceforge / feature requests]

### ISSUE THREAD

**Issue by chuchana** [LispCookbook/cl-cookbook#14]
Hi, How do I set proxy host and port in CLISP? I tried setting _HTTP-PROXY_ but it didn't give any results for me.

[http://sourceforge.net/p/cl-cookbook/feature-requests/24/]

**Comment by vindarel** [comment]
Hi, how is it related to the cookbook ? I'm eager to close this.

**Comment by can3p** [comment]
My guess is that it could be an issue if some networking code does not respect system proxy settings

**Comment by vindarel** [comment]
I can't find an occurence of "proxy" in the cookbook and we can't ask the OP: let's close this.
