### ISSUE TITLE
LOOP Examples [from sourceforge / feature requests]

### ISSUE THREAD

**Issue by chuchana** [LispCookbook/cl-cookbook#15]
maybe the document found at 
http://www.ai.sri.com/~pkarp/loop.html
is fine as an answer to request 766293 ?

[John Thingstad @ http://sourceforge.net/p/cl-cookbook/feature-requests/22/]

**Comment by pnathan** [comment]
this will need to dig up the cross-reference to request 766293

**Comment by chuchana** [comment]
probably this: https://github.com/LispCookbook/cl-cookbook/issues/26

**Comment by vindarel** [comment]
some examples: http://articulate-lisp.com/examples/snippets.html#loop

**Comment by vindarel** [comment]
The loop page https://lispcookbook.github.io/cl-cookbook/loop.html actually uses the page given by Chuchana :) Well done.
