### ISSUE TITLE
Backquote excercise [from sourceforge / feature requests]

### ISSUE THREAD

**Issue by chuchana** [LispCookbook/cl-cookbook#16]
The chapter on macros at one point defines a simple
macro. Then the following excersise is given:

"Exercise: Try writing the new version of the macro
without using backquote. If you can't do it, you have
done the exercise correctly, and learned what backquote
is for!"

Why I'm supposed not to be able to convert the macro?

---

Drew McDermott: If you can do it without backquote, that's great! It's just an annoyingly 
difficult chore, so it shows you why backquote is so useful.

[http://sourceforge.net/p/cl-cookbook/feature-requests/21/]

**Comment by pnathan** [comment]
Looks like Drew covered this issue. But it'd be nice to have the answer in a "Answers" section.

**Comment by alxnorden** [comment]
Request for comment:

1) should Answers section be added to the Macros chapter? 
Should this be done with a hidden css tag, or simply at the end of the chapter?

2) should Answers / Exercises be added to other sections of the book? Currently it appears only the Macros chapter has exercises.

**Comment by vindarel** [comment]
For me the exercisms/answers make not much sense. And the macros section should be rewritten.There's room for improvement.
