### ISSUE TITLE
Math Chapter [from sourceforge / feature requests]

### ISSUE THREAD

**Issue by chuchana** [LispCookbook/cl-cookbook#17]
It would be great to have a cookbook chapter on
mathematics.

1) how to do arithmetic with integers, floats.
2) difference between single and double percision
3) examples with integers and bignums,
how to implement infinite percision float with bignums.
4) matrix calculations with lists and with 2-d arrays, 
sparse matrix calculations with hash tables
optimizations and declarations
5) transcendentals (not sure if this is useful because you 
can easily look up all the functions sin, cos, tanh 
exp etc...
6) Complex numbers
7) CLOS methods specializing on different classes of
numbers

[http://sourceforge.net/p/cl-cookbook/feature-requests/19/]

**Comment by pnathan** [comment]
Math operations are tricky to do correct. Someone who knows what they are doing should really manage this.

**Comment by vindarel** [comment]
All done by @bendudson in https://lispcookbook.github.io/cl-cookbook/numbers.html and https://lispcookbook.github.io/cl-cookbook/arrays.html
