### ISSUE TITLE
Build PDF Bundle

### ISSUE THREAD

**Issue by jmercouris** [LispCookbook/cl-cookbook#176]
Is there a way to build a PDF bundle directly from these sources? Maybe these could be uploaded to releases and versioned?

**Comment by vindarel** [comment]
+1 that would be nice. But at that point we might want to use a proper editing system, one that also builds TOCs, provides a search,… (à la git-books).

**Comment by jmercouris** [comment]
Would you be interested in a fork that merges everything into one giant org file? Do you use emacs?

**Comment by pnathan** [comment]
All the current MD files into *one* giant ORG file? 

I am *extremely* disinterested in that level of coupling between articles. 

A build process that gathers up the MD files and builds out what is required for search, TOC, etc, is substantially better.

**Comment by jmercouris** [comment]
If it makes one long pdf, search should be very easy. I don’t think the size of the cookbook merits some sort of dynamic search, I really think all of it could just be a plaintext file

**Comment by vindarel** [comment]
Yes I use Emacs (and org-mode too).

> A build process that gathers up the MD files and builds out what is require

agreed

But you can try and build the pdf out of it :) (although converting md to org may not be funny)

> I don’t think the size of the cookbook merits some sort of dynamic search, I really think all of it could just be a plaintext file

oh ok, anyway an _online_ search would be a bonus brought by a proper content management system, not one to focus on.

**Comment by bendudson** [comment]
This may not be a direction you want to go in, but I have found readthedocs to be quite good. It provides online search, links to github, but does mean putting everything into rst format.

**Comment by pnathan** [comment]
> everything into rst format.

rst is incredibly fiddly. I've used it previously as part of a big project and really, I could never recommend using it. 

that said, I think I'll have some time coming up to hack on this. (famous last words, *pnathan was never heard from again*). 

https://github.com/abeMedia/jekyll-pdf  I think I'll look into this.

**Comment by jmercouris** [comment]
+1, I've had bad experience with RST. The syntax is just so unwieldy sometimes, especially for things like code blocks and weird spacing requirements.

@pnathan 

How about a script that just concatenates all of the MD files together and produces a PDF, one needn't adjust the structure of this repository, no?

**Comment by pnathan** [comment]
@jmercouris that's the direction I'm sorta thinking is idealish

**Comment by jmercouris** [comment]
Great! Well, maybe one of us will find the motivation to do it :P I'll make a PR if I do

**Comment by jmercouris** [comment]
I tried some basic stuff with pandoc:

[numbers.pdf](https://github.com/LispCookbook/cl-cookbook/files/2103155/numbers.pdf)

lots of issues. Also, many files did not even compile at all.

**Comment by vindarel** [comment]
Any progress here ? @pnathan, did you have some time this time ? :) @jmercouris Is it better after the CLOS rewrite ? (that is cleaner now)

**Comment by jmercouris** [comment]
@vindarel 

seems that those changes have been effectively at least with regard to clos, here you can see the PDF now rendered with CLOS in it:

[cookbook.pdf](https://github.com/LispCookbook/cl-cookbook/files/2468475/cookbook.pdf)

**Comment by vindarel** [comment]
Hello ! With two more sections added recently it would be awesomer-than-ever to have a pdf. Any progress someone ?
