### ISSUE TITLE
ILSIP Installation [from sourceforge / feature requests]

### ISSUE THREAD

**Issue by chuchana** [LispCookbook/cl-cookbook#19]
Hi,
Two things as detailed below.

Cheers, Doug

doug.mein@dspace.com.au

ps: I am new to this, so I hope I'm making some sense 
to you :)

1st Thing:
I have installed Emacs, ILISP and CL. Everything look OK 
but i get a couple of errors when i start up ILISP in 
Emacs (by pressing F5).

Here are all the messages. You can see the errors at 
the end.

So, all the obvious questions - Should I be worried 
about these errors? What do I need to do to do to fix 
them? Why is ILISP initializing twice?

(C:\bin\emacs-21.3\bin\emacs.exe)
Loading regexp-opt...done
Loading image...done
Loading cl-macs...done
Loading c:/home/.recentf...done
Loading pc-select...done
Loading delsel...done
Loading paren...done
Loading advice...done
Reading directory c:/home/...done
For information about the GNU Project and its goals, 
type C-h C-p.
Loading ilcompat...
Loading ilfsf21...done
Loading ilcompat...done
Loading comint-ipc...done
Loading extra/hyperspec...
Use C-u M-x make-directory RET RET to create 
directory and its parents
Loading extra/hyperspec...done
Loading extra/cltl2...done
Loading ilisp-all.elc...
Loading cl-seq...done
Loading ilisp-all.elc...done
Loading menu interface.
'ilisp-*enable-cl-easy-meny-p*' is t
Loading ilisp-cl-easy-menu (source)...done
Loading ild...done
Loading ilisp-imenu...done
Loading outline...
Loading easy-mmode...done
Loading outline...done
Started initializing ILISP [2 times]
Aborted commands
error in process filter: file-name-hack: Symbol's function 
definition is void: replace-in-string
error in process filter: Symbol's function definition is 
void: replace-in-string
Set *clisp-hs*'s directory to c:/home/

2nd thing:

Is the following normal?

Starting c:/bin/clisp-2.33.1/full/lisp.exe -B c:/bin/clisp-
2.33.1/full/ -M c:/bin/clisp-2.33.1/full/lispinit.mem -ansi -
q ...
ILISP V5.12.0 Use M-x ilisp-bug for problems and 
suggestions.
;; Loading file C:\home\_clisprc.lisp ...
;; Loaded file C:\home\_clisprc.lisp
[1]> 
[2]> (defvar"at this point i can't enter a space and get -
-> file-name-hack: Symbol's function definition is void: 
replace-in-string, and now having added this comment is 
can continue typing e.g." x 1)
*** - DEFVAR: non-symbol "at this point i cant't enter a 
space and get --> file-name-hack: Symbol's function 
definition is void: replace-in-string, and now having 
added this comment is can continue " cannot be a 
variable (Obviously)
Break 3 [8]> 
"if i go to a blank line things are ok"
Break 3 [8]>
(defvar x 1) 
X
Break 3 [8]> 
x
1
Break 3 [8]>

[http://sourceforge.net/p/cl-cookbook/feature-requests/17/]

**Comment by pnathan** [comment]
Quite superseded by SLIME.
