### ISSUE TITLE
Roadmap and README file

### ISSUE THREAD

**Issue by vityok** [LispCookbook/cl-cookbook#2]
is there any kind of a roadmap with the list of issues that should be addressed - like reformatting from HTML to some other format to make it work nicely with githib books?

ideas how to improve contents of the book?

**Comment by pnathan** [comment]
I have not compiled such. One idea might be to import the SF list of bugs & features and work from there.

 @eudoxia0 what do you think here?

**Comment by eudoxia0** [comment]
i would probably start there, yeah.

then maybe start moving the HTML to Jekyll so its built automatically.

**Comment by pnathan** [comment]
this is done
