### ISSUE TITLE
String section addition [from sourceforge / feature requests]

### ISSUE THREAD

**Issue by chuchana** [LispCookbook/cl-cookbook#20]
I'm just getting into lisp, and I was very surprised by
the lack of a function in the ANSI standard for
replacing subsections of vectors (strings) with other
vectors. In C#, you can do something like

```
mySqlQuery.Replace("'", "\'")
```

to make it safe for inserting into a DB, and quoting
like that is something you do in tons of places in web
programming. So I think you should include a function
for replacing things in vectors like this. I found this
function on http://www.lisp-p.org/lht/, by Gene Michael
Stover (it was called "string-replace-all-faster" there).

```
(defun string-replace-all (source old new)
"Replace all occurrences in 'source' of 'old' with
'new'."
(do ((newlen (length new))
(i (search old source)
(search old source :start2 (+ i newlen))))
((null i) source)
(setq source
(concatenate 'string
(subseq source 0 i)
new
(subseq source (+ i newlen))))))
```

I haven't gotten his permission for anything, I just
found it. I modified the doc string a bit, and I
changed the order and name of the arguments, and the
name of the function.

Maybe there's a library of basic string functions
somewhere you could link to on the string page.

[Chris Capel @ http://sourceforge.net/p/cl-cookbook/feature-requests/16/]

**Comment by vindarel** [comment]
+1 for the need ! Looks like there is what's needed now: https://lispcookbook.github.io/cl-cookbook/strings.html in two libraries: https://github.com/diogoalexandrefranco/cl-strings and https://github.com/vindarel/cl-str#replace-old-new-s

Good to close this ?
