### ISSUE TITLE
add select() function to sockets section [from sourceforge / feature requests]

### ISSUE THREAD

**Issue by chuchana** [LispCookbook/cl-cookbook#21]
Please add a note of the Lisp equivalent of the C select() function to 
the Sockets Section.

[http://sourceforge.net/p/cl-cookbook/feature-requests/15/]

**Comment by pnathan** [comment]
The Sockets section is based on CLOCC: http://clocc.sourceforge.net/ . I am unfamilar with that project. A brief Googling and archive perusal suggests that it's still around, but not super popular.

**Comment by eudoxia0** [comment]
We should use usocket.
