### ISSUE TITLE
regex in the strings section [from sourceforge / feature requests]

### ISSUE THREAD

**Issue by chuchana** [LispCookbook/cl-cookbook#22]
Strings aren't complete without a regular expression
engine!

I think it would be a great service to mention one of
them, I personally use cl-ppcre (
http://www.weitz.de/cl-ppcre/ ) which has completely
eclipsed all other string handling for me, it's really
a savior and bitch'in fast. :-)

Yes, I'll volunteer to write it too.
- Heow h e o w at a l p h a g e e k s i n c
  dot c o m

[Heow Eide-Goodman @ http://sourceforge.net/p/cl-cookbook/feature-requests/14/]

**Comment by eudoxia0** [comment]
We should definitely describe cl-ppcre

**Comment by vityok** [comment]
Worth to note that CL-PPCRE is not the only regex engine in the Quicklisp repository. A [small survey here](https://bitbucket.org/vityok/cl-string-match/wiki/Regular%20expressions%20in%20Common%20Lisp). However, CL-PPCRE became a de-facto standard recently.

**Comment by vindarel** [comment]
cl-ppcre is mentioned now in https://lispcookbook.github.io/cl-cookbook/pattern_matching.html (pattern matching & regular expressions). It's also mentioned once in the strings page. So I close this ok ?

**Comment by pnathan** [comment]
cl-ppcre is The Standard.
