### ISSUE TITLE
Need info on how to load init files for CLISP [from sourceforge / feature requests]

### ISSUE THREAD

**Issue by chuchana** [LispCookbook/cl-cookbook#23]
Using Xemacs 2.4.13 on WinXP, with ILISP 5.12 and CLISP
2.30. Can start CLISP in inferior process, but get
error that CLISP cannot find init files (e.g.
ilisp-pkg.lisp). Appears to be due to fact that file
name being passed to CLISP includes '\' as path
separator, instead of '/'. Have done some research in
ilisp-snd.el and ilisp-hi.el, but have not figured out
how to prevent file name problem.

[Alexander Stockdale @ http://sourceforge.net/p/cl-cookbook/feature-requests/13/]

___________________________

Discussion:

Nobody/Anonymous:
Are you using the Win32 version of CLISP or are you running
a Unix-y version under cygwin? I think one difference is in
the way path separators are handled. -win32.zip, not tar.gz.
That's just a vague recollection, hope it works.

Alexander Stockdale:
In answer to the question, I am using the win32 version of 
CLISP. Further update: I think I have solved the problem (or 
at least, found a fix). I modified file-name-hack in ilisp-hi.el 
to check for system-type of 'windows-nt, and ilisp-dialect 
of 'clisp-hs. If both conditions satisfied, I use replace-in-
string to change &quot;\\&amp;quot; to &quot;/&quot;.
This may not be the most elegant fix, but it works, and at 
least the changes are localized to a function that already 
kludges filenames.

Alexander Stockdale:
Attaching a copy of a modified ilisp-hi.el with hack so that
init filenames can be handled by clisp.

Alexander Stockdale:
Modified ilisp-hi.el with hack so that init filenames are passed to CLISP in a format it can handle.

http://sourceforge.net/p/cl-cookbook/feature-requests/_discuss/thread/82f87c3e/39b1/attachment/ilisp-hi.el / https://gist.github.com/chuchana/82b6dcb4f5cdf3641906

**Comment by pnathan** [comment]
ILISP is superseded by SLIME.
