### ISSUE TITLE
Merging more content in?

### ISSUE THREAD

**Issue by pnathan** [LispCookbook/cl-cookbook#236]
Hi,

I built run http://articulate-lisp.com/, which I consider .... sort of done, I guess. It is useful content. I get about 200 "users" per month.

But frankly, with the contribution and community that's formed around the cookbook, I think I should turn over Articulate Lisp's content to the cookbook and redirect users to it.

What do you think, @eudoxia0 @vindarel @sheepduke (other thoughts solicited)

**Comment by sheepduke** [comment]
If I understand it correctly, this site is more for newbie users, right?

In my humble opinion, it would be great to integrate the content into the Cookbook, since there are some content already existing in the Cookbook. 

But I am afraid that Jekyll may not be as flexible as a stand-alone web page. For example the top menus will disappear...

Maybe a re-designed separate starter section would solve the problem?

**Comment by vindarel** [comment]
Hello,

> sort of done

yes, but with issues :) 

https://github.com/articulate-common-lisp/articulate-common-lisp.github.io/issues/68

>  I think I should turn over Articulate Lisp's content to the cookbook and redirect users to it.

Well you could advertise the Cookbook for a start, indeed :) 

It seems wiser to give priority to the Cookbook for things that evolve, like core stuff tutorials (setting up an environment, ide selection). But shorter articles also have their public. I like very much the opinionated articles though, like the LispWorks review. I also liked walk-through of code, like the trotter example, that wouldn't fit in a Cookbook recipe (or would it?). I only call for more. Both could be a force to articulate-cl.

**Comment by phoe** [comment]
> Well you could advertise the Cookbook for a start, indeed :)

It is already getting advertised a little bit: https://news.ycombinator.com/item?id=19987804

**Comment by vindarel** [comment]
Coool :) (I meant, on articulate-cl front page.)

**Comment by pnathan** [comment]
@sheepduke I'd just copy the content over and integrate it. 

@vindarel yeah... I wound up in a situation for about 20 months where at-home work for anything kinda slid.

You have a good point that there's things which aren't going to fit more in the Cookbook.
