### ISSUE TITLE
Configuring Xemacs for Clisp [from sourceforge / feature requests]

### ISSUE THREAD

**Issue by chuchana** [LispCookbook/cl-cookbook#24]
Can SomeOne explain me How to

Configure Xemacs for Clisp. I found The Article

&quot;Setting up an IDE with Emacs on Windows&quot;

But this doesnt wok witk my Xemacs

I suppose this Article works only wirth Emacs.

Thank You for your Help

____________________________

Alexander Stockdale:
The sample .emacs file doesn't work, but the instructions in
general are correct. I made some progress by using the
ilisp.emacs file in the ilisp directory (look in
xemacs-packages/lisp) as a template for my init.el file. 
Still having problems (as described elsewhere) with CLISP
not loading the init files properly.

[ek @ http://sourceforge.net/p/cl-cookbook/feature-requests/12/]

**Comment by pnathan** [comment]
Is XEmacs still a thing? Most people I've run into the past 5 years do not use Xemacs. The bug was originally filed in 2003, 12 years ago. Closing as won'tfix until some XEmacs user cares to push forward on it.
