### ISSUE TITLE
Distributing small-sized executables with fasl ?

### ISSUE THREAD

**Issue by vindarel** [LispCookbook/cl-cookbook#240]
https://www.reddit.com/r/lisp/comments/bzctu1/dynamically_linking_sbcl_in_savelispanddie/

>  Most of the size is in the standard library. Creating a single .fasl from an ASDF bundle (search for "compile-bundle-op" on https://common-lisp.net/project/asdf/asdf/Predefined-operations-of-ASDF.html) may be close to what you want.

**Comment by pnathan** [comment]
:+1:

**Comment by vindarel** [comment]
I give up, after a failing test (my fasl wasn't executable as-is) (see reddit). Support on this is hard. And anyway, fasls are not portable.

> FASLs are not, to my knowledge, executable. monolithic-bundle-op ought to be runnable with sbcl's runtime though. Downside is that IIRC FASLs are not portable between different builds of SBCL (other lisp implementations may be more forgiving on portability of FASLs; you can bundle it into a single .lisp file which will be highly portable, but slower to load).
