### ISSUE TITLE
Examples on `iterate`

### ISSUE THREAD

**Issue by digikar99** [LispCookbook/cl-cookbook#243]
While exploring [The Iterate Manual](https://common-lisp.net/project/iterate/index.html), I created [this page on iterate](https://digikar99.github.io/cl-iterate-docs/), and shared it over [reddit](https://www.reddit.com/r/Common_Lisp/comments/bzw7l2/some_more_documentation_for_iterate_i_came_across/). [u/dzecniv](https://www.reddit.com/user/dzecniv/) suggested may be add it over here - I agree that I'd like to find all the Common Lisp content at one page. So, a request for addition of those examples over here.

I also see that [this issue is still open](https://github.com/LispCookbook/cl-cookbook/issues/168).

**Comment by vindarel** [comment]
Hey, that would be an awesome addition. You can create a new page, and don't hesitate to add examples to the iteration one.

**Comment by vindarel** [comment]
Hey, just discovered this: https://sites.google.com/site/sabraonthehill/loop-v-iter (this website has awesome articles)

**Comment by arademaker** [comment]
Nice blog posts, it worth cite them but it would be good to keep the material self-contained.
