### ISSUE TITLE
TOC now visible on small screens

### ISSUE THREAD

**Issue by digikar99** [LispCookbook/cl-cookbook#244]
I really like the Cookbook's Design - the sidebar in particular, and have been using it wherever possible. 

I noted that TOC has been hidden on small screens, and making it visible caused some issues. This has been fixed on [this fork](https://github.com/digikar99/cl-cookbook). The preview is [here](https://digikar99.github.io/cl-cookbook/getting-started.html). Let me know if I can issue a PR, and if there are any specific instructions - I see that there are several branches, and while forking, the branch for website defaulted to `gh-pages`.

**Comment by pnathan** [comment]
You can definitely submit a PR!

**Comment by digikar99** [comment]
#246 PR created

**Comment by sheepduke** [comment]
Nice work, thank you.

By the way is it possible to make the ToC button pop (expand?) a floating window containing the ToC when clicked?

I know GitBook has a plugin to do so.

IMHO it is more convenient...any idea?

**Comment by digikar99** [comment]
I assume you are referring to the usual menu bar at the top - expanding from the right in the case of gitbook.

Would something like this do? (Waiting for review, after a few unintended changes. Not too experienced with git; I think I should ideally make use of `git branch` here, but then, I can only display the website from one branch.) 

<p align="center">
  <img width="180" height="320" src="https://user-images.githubusercontent.com/31390273/59741442-a3a1ac80-9288-11e9-9b0a-c6e6bd6c0734.png">
</p>

The `toc-container` expands up from the bottom (or hides), when the `toc-btn` is tapped. (I personally like buttons at the bottom - easier to reach - but can be unintuitive at times. But, of course, the locations and expand directions can be changed.)

Also, I am not too good with colors - and the colors for the button and "Table of Contents" don't seem to look too good. Any suggestions?

**Comment by sheepduke** [comment]
On 2019-06-18 23:29, digikar <notifications@github.com> wrote:
> I assume you are referring to the usual menu bar at the top - expanding from the right in the case of gitbook.
>
> Would something like this do? (Waiting for review, after a few unintended changes. Not too experienced with git; I think I should ideally make use of `git branch` here, but then, I can only display the website from one branch.) 
>
> <p align="center">
>   <img width="180" height="320" src="https://user-images.githubusercontent.com/31390273/59741442-a3a1ac80-9288-11e9-9b0a-c6e6bd6c0734.png">
> </p>
>
> The `toc-container` expands up from the bottom (or hides), when the `toc-btn` is tapped. (I personally like buttons at the bottom - easier to reach - but can be unintuitive at times. But, of course, the locations and expand directions can be changed.)
>
> Also, I am not too good with colors - and the colors for the button and "Table of Contents" don't seem to look too good. Any suggestions?
>
>
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/LispCookbook/cl-cookbook/issues/244#issuecomment-503425760

That is exactly what I was thinking about. I think it is more convenient
than simply jumping back to the top of the page, e.g. when it is needed
to quickly jump between topics.

IMHO it is more convenient to put the button bottom-left or
bottom-right that does not block the content?

I think the color is fine. Waiting for more reviews.

P.S. As for the Git, if you would like to know more there is a website I found beginner-friendly: https://learngitbranching.js.org/
It takes several hours to finish. You may play Git games on it to understand git concepts and operations.

**Comment by vindarel** [comment]
LGTM. Ok, let's merge everything in one branch, no problem.

(it doesn't show on large screens, that always show the toc on the sidebar)

**Comment by digikar99** [comment]
> IMHO it is more convenient to put the button bottom-left or
bottom-right that does not block the content?

Okay, put it on the bottom-right - the menu / TOC opens from the right. This seems more intuitive than having the button at the very bottom.

> P.S. As for the Git, if you would like to know more there is a website I found beginner-friendly: https://learngitbranching.js.org/

Thanks for the link; will check it out!

> (it doesn't show on large screens, that always show the toc on the sidebar)

Didn't get this. Could you please elaborate?

**Comment by vindarel** [comment]
> Didn't get this. Could you please elaborate?

sorry. I was just explaining to others that your change didn't affect the case when we read on large screens. Because we only see the button on small screens.

But now it does:

![Selection_003](https://user-images.githubusercontent.com/3721004/60023500-3467f600-9696-11e9-95a1-9811baa03fc8.png)

**Comment by digikar99** [comment]
Fixed. Now it only shows on small screens, provided the pathname is not "/cl-cookbook/". This is handled by `assets/toggle-toc.js`.

**Comment by vindarel** [comment]
> provided the pathname is not "/cl-cookbook/"

hu ? So mobile users reading the pages on https://lispcookbook.github.io/cl-cookbook/ can't see it ?

**Comment by digikar99** [comment]
> hu ? So mobile users reading the pages on https://lispcookbook.github.io/cl-cookbook/ can't see it ?

Oh, apologies for the confusion - for the exact pathname "/cl-cookbook/", no (because there's no TOC for the home page), but for pathnames like "/cl-cookbook/getting-started.html", the button is visible.

**Comment by vindarel** [comment]
but I can't see it on your page when I stretch to a small window: https://digikar99.github.io/cl-cookbook/getting-started.html

**Comment by digikar99** [comment]
> but I can't see it on your page when I stretch to a small window: https://digikar99.github.io/cl-cookbook/getting-started.html

It should require a page refresh.

**Comment by vindarel** [comment]
ok it works now.

Shall the TOC disappear once we clicked a link ? Currently we have to re-click on the button to hide it.

**Comment by digikar99** [comment]
> Shall the TOC disappear once we clicked a link ? Currently we have to re-click on the button to hide it.

That, and a few more changes to hide it as per intuition have been made.

**Comment by vindarel** [comment]
Good stuff, nice work !
