### ISSUE TITLE
`lispcookbook.dev`

### ISSUE THREAD

**Issue by pcr910303** [LispCookbook/cl-cookbook#249]
As a person who loves Common Lisp (and the CL cookbook project), I thought that a dedicated URL such as `lispcookbook.dev` will be better. (I always forget the `/cl-cookbook/` part when I type in the URL...)

Before buying the URL myself, I thought that asking the project maintainers would be better.
If I buy the URL, will the maintaners setup the gh-pages appropriately?̊̈

Sorry for my bad English :-(

![스크린샷 2019-06-20 오전 9 16 54](https://user-images.githubusercontent.com/37990858/59809661-83cbc080-933c-11e9-8af3-f37404ae18c4.png)

**Comment by sheepduke** [comment]
Hmm...Actually it is possible to simply remove the `/cl-cookboko/` part.
Personally I would say it seems to have little sense since the `cookbook` is already in the URL.

@vindarel Do you think it is better to remove it?

**Comment by vindarel** [comment]
Hi guys,

> it is possible to simply remove the /cl-cookboko/ part.

Is it ? I don't think so. It's an url built by gh pages and I see no setting to remove this suffix.

Then, we must keep the current url, obviously. So we could have both. You could buy the domain and make an invisible redirection to here. But then, this raises the question of its usefulness and of its property. How would we, the group of maintainers, share the rights on this new domain, practically speaking ?

ps:

> (I always forget the /cl-cookbook/ part when I type in the URL...

but why type it ? :]

**Comment by sheepduke** [comment]
> Is it ? I don't think so. It's an url built by gh pages and I see no setting to remove this suffix.
>
I would say yes. There is a configuration located at `_config.yml` file. It is configured as below:

```
baseurl: "/cl-cookbook"
```

It is possible to set it to `""` so that simply `lispcookbook.github.io` should work.

I have tested the result on my local machine and I did not need to type `/cl-cookbook` any more.

**Comment by vindarel** [comment]
Good find. But old links (with the "/cl-cookbook" part) will be broken, right ?

**Comment by sheepduke** [comment]
On 2019-06-24 13:59, vindarel <notifications@github.com> wrote:
> Good find. But old links (with the "/cl-cookbook" part) will be broken, right ?
>
Yes. Unless GitHub pages have the function to set redirect or something.

But the current URL is really verbose :-(

**Comment by vindarel** [comment]
So, you can still buy the domain and make an invisible redirection.

Thanks for asking !
