### ISSUE TITLE
simple log parser example [from sourceforge / feature requests]

### ISSUE THREAD

**Issue by chuchana** [LispCookbook/cl-cookbook#25]
It would be very helpful to have even a very simple example
of an efficient (again simple) log parser.
Looking at cl-httpd's common-log-parser isn't helpful
at all, because
it's _quite_ complex..

---

Ross Lonstein:
Log parsing is just string parsing and file manipulation.

The below can be used in place of awk for the very simple case of extracting columns from the 
interesting lines of a file (those matching a simple string):

```
(defun split (delim line)
"Return a list of subsequences separated by a one character delimiter, delim itself is not returned"
(loop :for mark = 0 :then (1+ point)
:for point = (position delim line :start mark)
:collect (subseq line mark point)
:while point))

(defun splitcols (columns file &key (delim #\Space) grep)
"Iterate over the lines of a file, returning the specified columns.
If :grep is supplied only lines containing that string will be returned."
(with-open-file (s file)
(loop :for line = (read-line s nil)
:while line
:when (or (eq grep nil) (search grep line))
:collect (loop :with chunks = (split delim line)
:for c :in columns
:collect (elt chunks c)))))
```

This is not particularly efficient. On my machine, comparing awk (including startup) to 
SBCL 1.0.18 (not including startup) and sinking the output shows awk to be more than 3x
faster.

[http://sourceforge.net/p/cl-cookbook/feature-requests/11/]

**Comment by eudoxia0** [comment]
I think this is a bit too specific.

**Comment by vityok** [comment]
However, it is an interesting topic that overlaps with other text processing and text IO areas (like efficient parsing of CSV files, etc.)

There is, however, no "simple" way (at the moment) to handle logs and other massive amounts of text data in Common Lisp.

Recently a question about parsing CSV sparked an [intensive discussion on comp.lang.lisp.](https://groups.google.com/d/msg/comp.lang.lisp/8nzWKfdSySM/jQuaVBQpkMEJ)

**Comment by vindarel** [comment]
@vityok we saw two new log parsers lately, for apache and nginx logs: http://www.cliki.net/pml hope that helps.

**Comment by vindarel** [comment]
so this is too specific and we have external tools as examples. Closing.
