### ISSUE TITLE
search/index

### ISSUE THREAD

**Issue by markboston34** [LispCookbook/cl-cookbook#252]
it would be great if the site had a good search. it kind of does have an index now but im thinking of a real index where you hit a for all the topics that begin with a etc.

but search should really be pushed as a feature. i want to look something up either i need to use google(which is ok) or i need to wade through a bunch of stuff to find what im looking for.

**Comment by vindarel** [comment]
We can easily add a Duckduckgo searchbox: https://vindarel.github.io/cl-cookbook/
