### ISSUE TITLE
Contrib Offer, I wrote a small WebSocket Tutorial using Hunchensocket

### ISSUE THREAD

**Issue by thegoofist** [LispCookbook/cl-cookbook#255]
Greetings!

Here (https://github.com/thegoofist/hunchenchat-demo) is an adaptation of the hunchensocket maintainer's demo that I think might be a good starting point for a Cookbook entry.

It uses SBCL and has been tested on Linux.

Critiques and suggestions welcome!

**Comment by mohe2015** [comment]
This is really a big thing and I think even cl-cookbook doesn't really care but it is recommended to use clack https://borretti.me/article/common-lisp-sotu-2015 as an abstraction layer. For websockets this would probably be https://github.com/fukamachi/websocket-driver/blob/master/README.md but I don't know how ready this is. But as the cl-cookbook doesn't do that and clack's documentation is admittedly not so good I think adding your work would still be a good idea (I didn't look at the code!).

**Comment by sheepduke** [comment]
On 2019-08-06 02:11, Moritz <notifications@github.com> wrote:
> This is really a big thing and I think even cl-cookbook doesn't really care but it is recommended to use clack https://borretti.me/article/common-lisp-sotu-2015 as an abstraction layer. For websockets this would probably be https://github.com/fukamachi/websocket-driver/blob/master/README.md but I don't know how ready this is. But as the cl-cookbook doesn't do that and clack's documentation is admittedly not so good I think adding your work would still be a good idea (I didn't look at the code!).
>
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/LispCookbook/cl-cookbook/issues/255#issuecomment-518583550

https://github.com/LispCookbook/cl-cookbook/pull/182

It is an introduction of `usocket`, which IMHO is the de facto socket
library.

I totally understand the value of Clack, so how is websocket-driver?

**Comment by mohe2015** [comment]
> I totally understand the value of Clack, so how is websocket-driver?

As far as I understand it (I never used it) it abstracts away the different websocket implementations of Hunchentoot, Wookie and Woo. Websockets are different to normal sockets so usocket should not work.

**Comment by thegoofist** [comment]
Indeed, I  had initially chosen `websocket-driver` as well, but chose `Hunchensocket` simply b/c the Hunchentoot ecosystem is better documented, and because Hunchentoot lets me run two separate server processes from the same Lisp image.

One problem that I had with clack is that I could not define both the web server process and he websocket server process from the same REPL session.  I really believe that doing so should be possible, but I couldn't tell from the documentation how to do it. So I chose hunchentoot and hunchensocket instead because it was more straightforward.

**Comment by thegoofist** [comment]
Well, if there are no objections at the moment, I will reformat as Markdown (from org-mode) and put in an PR, where, perhaps further discussion will ensue. :) Probably this weekend.

**Comment by vindarel** [comment]
Great, please do. Maybe just mention websocket-driver and explain as you did here why you didn't choose it.

On style: we prefer `lowercase function names` rather than `UPPERCASE`.
