### ISSUE TITLE
SBCL core compression

### ISSUE THREAD

**Issue by vindarel** [LispCookbook/cl-cookbook#262]
```
#+sb-core-compression
(defmethod asdf:perform ((o asdf:image-op) (c asdf:system))
  (uiop:dump-image (asdf:output-file o c) :executable t :compression t))
```

From 120MB to 23MB, for a dozen milliseconds loss of startup time, still under the 50ms bar.

cc @ambrevar

**Comment by Ambrevar** [comment]
Yes, yes, yes, this _must_ be added to the cookbook!  I've been wondering how to do it for a year, it's incredibly well hidden deep in the tribal ASDF knowledge :p (Unless I've missed some obvious documentation).

By the way, the exampmle @vindarel mentions is about [Next](https://next.atlas.engineer) 's executable.

**Comment by Ambrevar** [comment]
Core compression is an SBCL option that's disabled by default.
It must be enabled when building SBCL with

    --with-sb-core-compression

For users of OSes providing an out-of-date or poorly-built SBCL, they
can always use [Guix](https://guix.gnu.org) to install a nice SBCL
package.

(Or maybe roswell, don't know.)
