### ISSUE TITLE
Debug trick: Stepping

### ISSUE THREAD

**Issue by Ambrevar** [LispCookbook/cl-cookbook#266]
In the debug page, stepping only works if
`(declaim (optimize (speed 0) (space 0) (debug 3)))` is enabled for the compiler.
(At least for SBCL, your mileage may vary.)

A killer feature of stepping with SLIME is that it shows the source code and moves the point to the expression being evaluated.  It would be nice to show this too.

Besides I find the terminating comment inappropriate:
```
Stepping is useful, however it may be a sign that you need to simplify your function.
```
I don't see how that's true: you can step through into and out of function calls, so functions can be small and simple but you'd still like to see what's called and how things go at a very high level of precision.
In fact, I'd even encourage stepping as one of the first item on the page.

**Comment by vindarel** [comment]
Also to add:

- the LispWorks graphical stepper: http://www.lispworks.com/documentation/lw61/IDE-W/html/ide-w-496.htm
- the new https://github.com/joaotavora/sly-stepper
