### ISSUE TITLE
Hello World C++ to CLISP [from sourceforge / feature requests]

### ISSUE THREAD

**Issue by chuchana** [LispCookbook/cl-cookbook#27]
I saw the articles on how to implement a Windows 
window in LISP but, how could I implement a non-
formatting command window in C++. Make a simple edit 
box that I could type in (print &quot;hello lisp&quot;) and have 
CLISP run it and print out in another edit box.

In other words I want to use CLISP in my for &quot;run time 
user stuff&quot; in a afx C++ window.

[http://sourceforge.net/p/cl-cookbook/feature-requests/9/]

**Comment by pnathan** [comment]
Microsoft MFC (AFX stuff) is long-obseleted. If someone cares, they are welcome to contribute. Until then, closing this as won'tfix.
