### ISSUE TITLE
Mention rutils

### ISSUE THREAD

**Issue by vindarel** [LispCookbook/cl-cookbook#276]
It now has good documentation.

https://github.com/vseloved/rutils/blob/master/docs/tutorial.md

**Comment by sheepduke** [comment]
This should go to [awesome-cl](https://github.com/CodyReichert/awesome-cl), I suppose?

**Comment by vindarel** [comment]
thanks for the reminder, I added it. 

I think there's room for mentioning it in some places of the cookbook too, per topic. In the data structures: mention some rutils utilities for sequences, hash-tables, etc.
