### ISSUE TITLE
Remove references to no longer existing sockets.html page

### ISSUE THREAD

**Issue by mihaiolteanu** [LispCookbook/cl-cookbook#278]
The sockets.html page was removed with [910ea4c](https://github.com/LispCookbook/cl-cookbook/commit/910ea4c2129cef7815eff267991c89839ba8484e), but references to it are still present in the .md files.

In process.md,

```
you might be writing a server which needs to be able to respond to
more than one user / connection at a time (for instance: a web
server - see [this example](./sockets.html#server) on the Sockets
page);
```

In web-scraping.md,
```
(lquery:$  *parsed-content* "#content li a" (attr :href))
;; => #("license.html" "editor-support.html" "strings.html" "dates_and_times.html"
;;  "hashes.html" "pattern_matching.html" "functions.html" "loop.html" "io.html"
;;  "files.html" "packages.html" "macros.html"
;;  "/cl-cookbook/clos-tutorial/index.html" "sockets.html" "os.html" "ffi.html"
[..]
```
The last one I haven't checked and doesn't seem to be a big deal, but the first one leads to a "404 - file not found" error in the [threads page](https://lispcookbook.github.io/cl-cookbook/process.html).

**Comment by sheepduke** [comment]
Confirmed. Do you know the name of the new page?

**Comment by mihaiolteanu** [comment]
I don't think there is any at the moment. 

From what I see, there is talk about rewriting the sockets page in [#177](https://github.com/LispCookbook/cl-cookbook/issues/177), after it was removed in [#96], (https://github.com/LispCookbook/cl-cookbook/pull/96), but that issue is still open.

**Comment by sheepduke** [comment]
OK. I will simply remove the extra references for now.

Thank you!

**Comment by sheepduke** [comment]
Fixed in 40a2ddc.

I forgot to link this issue. ;-)

**Comment by sheepduke** [comment]
Problem fixed. Closing.

**Comment by vindarel** [comment]
Thanks. I finally merged the sockets page rewrite.
