### ISSUE TITLE
Describe the different common data structure / algorithm libraries. [feature requests]

### ISSUE THREAD

**Issue by chuchana** [LispCookbook/cl-cookbook#28]
Is there a library of functions that operate on abstract 
set and list types with pluggable implementations, like 
hash-sets, linked-lists, array-lists etc?

Manuel Simoni (manuels@users.sf.net)

---

Nobody/Anonymous:
There's at least AP5 at http://www.ap5.com/ , but that is 
generalized to the relational level of semantics. I believe that 
there is also an abstract types toy library, but I can't locate it at 
the moment; perhaps it's part of CLOCC.

**Comment by pnathan** [comment]
`cl-containers` works, in my experience, but the docs are limited.

**Comment by eudoxia0** [comment]
what about https://github.com/fare/lisp-interface-library

**Comment by pnathan** [comment]
LIL has, iirc, a slightly different set of data structures supported, and a unique style. 

Probably the thing to do is have a table describing the different common data structure / algorithm libraries.

**Comment by eudoxia0** [comment]
Right.

**Comment by vindarel** [comment]
common data structures: https://github.com/LispCookbook/cl-cookbook/pull/103 with links to FSet and Sycamore (also discussing and pointing to Lisp Interface Libraries and others) https://github.com/ndantam/sycamore.

**Comment by vindarel** [comment]
https://www.reddit.com/r/Common_Lisp/comments/6q3w6o/data_structures_the_common_lisp_cookbook/
