### ISSUE TITLE
using XEmacs based CL on PC [from sourceforge / feature requests]

### ISSUE THREAD

**Issue by chuchana** [LispCookbook/cl-cookbook#29]
do you have any idea how to configure the GNU XEmacs 
for WINDOWS to work with the CL programs?
I personally use xemacs-21.4.6.

Thanks.

__________________________

Alexander Stockdale:
I am in the process of trying to set up CLISP to work with
ILISP in Xemacs. The cookbook is helpful, but the .emacs
file seems to be GNU emacs specific. I've used the
instructions as a guide, rather than following them
slavishly. At this point, my only problem is that the init
files (ilisp-pkg.lisp, cl-ilisp.lisp, cl-chs-init.lisp) are
not being loaded properly by CLISP, apparently because the
'/' character in the ILISP directory path is being changed
to a '\', and subsequently dropped by CLISP. I'm
experimenting to see where the character translation is
happening, and how to prevent it. Any advice/solutions welcome.

[http://sourceforge.net/p/cl-cookbook/feature-requests/6/]

**Comment by pnathan** [comment]
ILISP is superseded.  Xemacs is getting out of date. 

Closing as won'tfix until someone contributes.
