### ISSUE TITLE
Mention Discord server somewhere?

### ISSUE THREAD

**Issue by sheepduke** [LispCookbook/cl-cookbook#295]
I joined the server for some time, but I recently found that it is more active than I thought.

https://discordapp.com/channels/297478281278652417

Should it be a good idea to mention it somewhere? So the newbies of Lisp have one more place to ask questions.

Or probably we should add a section to describe where Lisp hackers hang out.

**Comment by vindarel** [comment]
Why not a Community section in the index.

Or refer to https://github.com/CodyReichert/awesome-cl#community ?

**Comment by sheepduke** [comment]
On 2019-12-17 08:54, vindarel <notifications@github.com> wrote:
> Why not a Community section in the index.
>
> Or refer to https://github.com/CodyReichert/awesome-cl#community ?
>
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/LispCookbook/cl-cookbook/issues/295#issuecomment-566651255

Oh, I did not notice this on GitHub.

Will it be redundant if we write it again in Cookbook? Or probably give
a link about awesome-cl#community in Cookbook?

(By intuition I thought the awesome-cl only contains libraries.)

**Comment by vindarel** [comment]
If you think it makes sense then let's copy them. And it actually does, indeed.

**Comment by sheepduke** [comment]
> If you think it makes sense then let's copy them. And it actually does, indeed.
>
If we do so, we have to maintain 2 copies in the future.

It seems not a good idea then...

I think mentioning the link of awesome-cl#community in the beginner page
might be helpful.

Any idea?

**Comment by vindarel** [comment]
Any one of these that solve your initial observation will be good :) (duplication is not good, quick links with fewer clicks are also better…)

> the beginner page

? The index/main page ?
