### ISSUE TITLE
Update the out-of-date GETENV code snippet [from sourceforge]

### ISSUE THREAD

**Issue by chuchana** [LispCookbook/cl-cookbook#3]
I realize that the CL Cookbook appears to be moribund, but just in case someone does care, the ostensibly portable GETENV implementation at http://cl-cookbook.sourceforge.net/os.html is rather out of date and is missing support for several major implementations.
Here's a replacement implementation that has been correctly conditionalized for and checked/tested with all current open-source Common Lisp implementations of note:
https://github.com/dryproject/snippets/blob/master/common-lisp/getenv.lisp
It's placed in the public domain, so feel free to copy and paste it verbatim.

[Arto Bendiken @ http://sourceforge.net/p/cl-cookbook/bugs/23/]

**Comment by PuercoPop** [comment]
It would be better to just use uiop:getenv as it comes with asdf.

**Comment by pnathan** [comment]
Agreed, @PuercoPop
