### ISSUE TITLE
Please write about using a GUI toolkit [from sourceforge / feature requests]

### ISSUE THREAD

**Issue by chuchana** [LispCookbook/cl-cookbook#31]
Hello --
The documentation on using something like CLIM is
overwhelming. We need to simple tips on building GUIs,
simple examples.
Please choose a simple a Libre Software solution.
Thank you.

synthespian

[http://sourceforge.net/p/cl-cookbook/feature-requests/4/]

**Comment by pnathan** [comment]
- ltk solves (ish) this.
- shinmera has some solutions here as well, I think.

**Comment by chuchana** [comment]
http://shinmera.github.io/qtools/

**Comment by eudoxia0** [comment]
Yeah, we should definitely talk about qtools instead of ltk

**Comment by priyadarshan** [comment]
@shinmera has been working on (Portacle)[https://shinmera.github.io/portacle/] too.

**Comment by Shinmera** [comment]
Portacle isn't a GUI toolkit.

**Comment by priyadarshan** [comment]
Yes, just realised that. Sorry, wrong ticket.

It would be ncie to mention Portacle, though.

**Comment by pnathan** [comment]
I would encourage knowledgable interface/front end people to take a swing at it.

**Comment by vindarel** [comment]
Possibly of interest for the "History" appendix: https://www.reddit.com/r/lisp/comments/1jq5rk/common_lisp_gui_options/cbhh1y2/

> I don't buy that. Maybe I'm old, but I remember a time when there was a lot of GUI development done in Lisp and especially Common Lisp. It's not a technical problem, it's just lost or hidden art.

>   The first really interactive GUI Builder was written in Lisp. It was sold as a commercial with Common Lisp. Steve Jobs got a demo and hired the guy who wrote it. It's now Apple's Interface Builder.
> 
>   PTC has a complex CAD system with a very extensive user interface written in Common Lisp and C++.
> 
>   See Open Music and PWGL for very GUI intense applications written in LispWorks.
> 
>  Apple used MCL to write a bunch of applications. Microsoft used it to prototype MS Word User Interfaces on the Mac.
> 
>  ScroreCleaner is a Music Notation software written in LispWorks: https://www.youtube.com/watch?v=6IlOL1IOnHk
> 
> Actually writing GUI apps used to be a lot of fun. The commercial tools from Franz and LispWorks still support that. It might need to be rediscovered. Interactively develop GUI applications is much more fun than C++ or Java. It's just that currently the free libraries may not be there. That's why for example the larger and complex music applications, even if the code is free, are written mostly in LispWorks: Open Music, PWGL, ScoreCleaner, Igor Engraver, Symbolic Composer. Before that, people wrote those mostly in MCL - because that was cheaper and at that time there was no similar GUI-capable LispWorks on the Mac (which was popular at Universities and among musicians).
> 
> It's not that it wasn't tried. Open Music 5 for example had a version for SBCL/GTK. The current Open Music 6 is only for LispWorks.

**Comment by vindarel** [comment]
Good pointers from https://www.reddit.com/r/Common_Lisp/comments/ajaowa/selfcontained_crossplatform_gui_applications_with/ and https://www.reddit.com/r/lisp/comments/ajsoxa/example_on_how_to_use_java_swing_ui_within_abcl/

### tk doesn't necessarily look old

![](https://tkdocs.com/images/idleprefs_new_m.png)

[](https://www.reddit.com/r/lisp/comments/ajsoxa/example_on_how_to_use_java_swing_ui_within_abcl/)

https://en.wikipedia.org/wiki/Tk_(software)

> Since Tcl/Tk 8, it offers "native look and feel" (for instance, menus and buttons are displayed in the manner of "native" software for any given platform).[5] Highlights of version 8.5 include a new theming engine, originally called Tk Tile,[6] but now generally referred to as "themed Tk", as well as improved font rendering.[7] Highlights of version 8.6 include PNG support and angled text.[8] 

https://www.tcl.tk/software/tcltk/8.5.html (and screenshots)

### Swing with ABCL

https://github.com/defunkydrummer/abcl-jazz
