### ISSUE TITLE
cl-str vs. Serapeum

### ISSUE THREAD

**Issue by Ambrevar** [LispCookbook/cl-cookbook#310]
What do you people think of cl-str vs. Serapeum's string procedures?
They seem to overlap almost completely.
Any particular difference you'd be missing from one or the other?

Shall we recommend Serapeum in the strings chapter?

**Comment by vindarel** [comment]
I mentioned Serapeum, thanks.

It's true they're overlapping. Serapeum has some more macros (with-string, mapconcat, fmt…) and functions (tokens, word-wrap…), cl-str has insert, repeat, pad, s-first/last/rest/nth, unwords and unlines, remove-punctuation, s-assoc-value, string-case…

**Comment by Ambrevar** [comment]
Thanks for clarifying!
Cheers!
