### ISSUE TITLE
Dead link "Lisp Machines" found at page "Interfacing with your OS"

### ISSUE THREAD

**Issue by C-Entropy** [LispCookbook/cl-cookbook#311]
Here at [Interfacing with your OS](https://lispcookbook.github.io/cl-cookbook/os.html),I found a dead link: [Lisp Machines](http://kogs-www.informatik.uni-hamburg.de/~moeller/symbolics-info/symbolics.html)

**Comment by rprimus** [comment]
Thu Mar 12 14:12:59 GMT 2020

Archived version available at:

https://web.archive.org/web/20031204193219/http://kogs-www.informatik.uni-hamburg.de:80/~moeller/symbolics-info/symbolics.html
