### ISSUE TITLE
Translating it to Chinese

### ISSUE THREAD

**Issue by oneforalone** [LispCookbook/cl-cookbook#317]
I'd like to translate it to  Chinese, would that  be possible? Actually, I've already translated some chapters, but I don't know how to contribute to it.

**Comment by vindarel** [comment]
Hello,

That would be great, you are more than welcome to do it. 

The website doesn't have a structure for translations, yet, so I think the easiest is that you publish it on your side (you can use exactly the same structure and publish on Github Pages with another name, or use another static site engine as do the Brazilian community: https://github.com/commonlispbr/cl-cookbook), then give us the link and we show it on the front page.

We started discussing a website overhaul (#306), and with a better layout we could have links to translations on each page. For example, as here: https://docsify.js.org/#/cover (upper right corner) If/when we have it, then we could discuss either to merge chinese content, either to correctly link to the translation of each page.

**Comment by oneforalone** [comment]
Okay, I'll try on Github Pages first.

**Comment by oneforalone** [comment]
Hi, here is the Chinese Version: [https://oneforalone.github.com/cl-cookbook-cn](https://oneforalone.github.io/cl-cookbook-cn/#/), I tried JekyII, GitBook, docsify, and found that docsify is easy to use and works perfectly.

**Comment by vindarel** [comment]
Hey I can't get to have the "edit on github" corner, did you do something special? (are you using the docsify-edit-on-github-plugin? Can't make it work)

**Comment by oneforalone** [comment]
See [https://docsify.js.org/#/configuration?id=repo](https://docsify.js.org/#/configuration?id=repo), you need add your repo name in the `index.html`。
