### ISSUE TITLE
Database connectivity section

### ISSUE THREAD

**Issue by chuchana** [LispCookbook/cl-cookbook#32]
A &quot;Database connectivity&quot; section should be added using
the CLSQL library (by the UFFI author) before any
implementation specific methods.

http://clsql.med-info.com/

[Frederic Brunel @ http://sourceforge.net/p/cl-cookbook/feature-requests/3/]

**Comment by pnathan** [comment]
Is CLSQL still viable? I can't recall anymore.

**Comment by PuercoPop** [comment]
It is, it @AccelerationNet uses it and has some helper libraries. But idk it is the most popular choice nor that it should be the only one.

**Comment by eudoxia0** [comment]
We should use [cl-dbi](https://github.com/fukamachi/cl-dbi) and [sxql](https://github.com/fukamachi/sxql)

**Comment by vindarel** [comment]
I'm about to write about Mito and SxQL, telling you so than you can ping me if I'm long in doing so :)

**Comment by vindarel** [comment]
WIP: https://vindarel.github.io/cl-cookbook/databases.html (https://github.com/LispCookbook/cl-cookbook/compare/master...vindarel:database?expand=1)

**Comment by vindarel** [comment]
merged: https://github.com/LispCookbook/cl-cookbook/pull/175
