### ISSUE TITLE
Add Lisp Koans

### ISSUE THREAD

**Issue by phoe** [LispCookbook/cl-cookbook#328]
When https://github.com/google/lisp-koans/pull/111 is merged, I think that the Lisp Koans could be added as a learning resource.

**Comment by phoe** [comment]
The merge was done - I say we're good to go with adding the Koans.

**Comment by vindarel** [comment]
Fun fact: the issue on awesome-cl, that was resolved before this one, is number 327 https://github.com/CodyReichert/awesome-cl/issues/327
