### ISSUE TITLE
using functions provided by CLOCC [from sourceforge / feature requests]

### ISSUE THREAD

**Issue by chuchana** [LispCookbook/cl-cookbook#34]
Regarding the question Accessing Enviroment Variables
in Interfacing with your OS:

gut reaction: i found the answer scary.

hopefully costructive criticizem(sp?): CLOCC provides
getenv, which will work on more implementations than
the answer offered in the cookbook. I really believe
that it is important to point out already existing
solutions when they exist. CLOCC's getenv is setfable,
which, IMO, is more &quot;lispy&quot; than calling getenv with
one argument to get and two to set.

since CLOCC provides so many answers, maybe someone (i
will try when i have time) will just sit down and make
up the questions? if nothing else it will add a little
bulk to the cookbook in those areas where lisp seems ot
be laking (os interface/net &quot;stuff&quot;)

p.s. - thank you for the cookbook.

[http://sourceforge.net/p/cl-cookbook/feature-requests/1/]

**Comment by pnathan** [comment]
More CLOCCyness: http://clocc.sourceforge.net/

**Comment by vindarel** [comment]
closed by PR https://github.com/LispCookbook/cl-cookbook/pull/96
