### ISSUE TITLE
GUI Toolkits, minor things

### ISSUE THREAD

**Issue by lispm** [LispCookbook/cl-cookbook#341]
OpusModus is not written with CAPI & LispWorks. OpusModus is written in Clozure Common Lisp and with its toolkit, using Apple's Cocoa.

Additional on the commercial side is also Allegro CL's 'Common Graphics'.

https://franz.com/support/documentation/10.1/doc/contents.htm#cg

**Comment by vindarel** [comment]
Thanks.

**Comment by pnathan** [comment]
appreciate the bug report.
