### ISSUE TITLE
Deprecated CIM

### ISSUE THREAD

**Issue by fstamour** [LispCookbook/cl-cookbook#348]
Hello, just a heads-up;

The cookbook page on [continuous integration](https://lisp-lang.org/learn/continuous-integration) says to use [CIM](https://github.com/sionescu/CIM) but it's been deprecated (and abandoned AFAICT) since beginnig of 2017 (see [Deprecating CIM](https://keens.github.io/blog/2017/01/29/deprecating_cim/)).

This has caused me a few issues today, as one of the packages I was using required  a newer version of sbcl than what CIM installed.

Thanks

**Comment by fstamour** [comment]
> many existed before GitHub Actions, if you wonder
lol

That makes me think of all the times I had to explain that "GitHub" is _not_ "git".

> CL Foundation Docker images

For next time: maybe add a link to  [cl-docker-images](https://gitlab.common-lisp.net/cl-docker-images) in the references.

Thanks a lot for the changes!

**Comment by vindarel** [comment]
Hello, there's a link to https://hub.docker.com/u/clfoundation in the References, that's them!

Best,
