### ISSUE TITLE
Threads: mention cl-cpus wrt number of cores

### ISSUE THREAD

**Issue by phoe** [LispCookbook/cl-cookbook#354]
Currently, the Threads chapter mentions getting the CPU count in a possibly not-too-cross-platform way. And requires a C compiler.

I'd mention https://github.com/muyinliu/cl-cpus that does not require a C compiler or CFFI and works on macOS/Linux/Windows.

**Comment by vindarel** [comment]
Also Serapeum's count-cpus https://github.com/ruricolist/serapeum, cross-platform too.

**Comment by vindarel** [comment]
fixed by b9a5f45  process: rm C code & CFFI with serapeum:count-cpus
