### ISSUE TITLE
Fixed logo container causes issues on mobile devices

### ISSUE THREAD

**Issue by as-edrisy** [LispCookbook/cl-cookbook#365]
### https://github.com/LispCookbook/cl-cookbook/blob/ae9aa7ce4225991dfa2c67f15e8d02cfe23c65f8/assets/style.scss#L20

See also: https://i.imgur.com/3Cz3iI6.png

**Comment by vindarel** [comment]
Thanks for the report.

It's fixed… although the search input is hidden altogether on small screens now, it could appear somewhere…
