### ISSUE TITLE
Moving to Markdown

### ISSUE THREAD

**Issue by eudoxia0** [LispCookbook/cl-cookbook#37]
After #35 is done, we start turning the HTML into Markdown.

This is pretty extensive so any help is appreciated.

**Comment by chuchana** [comment]
I am currently converting 'hashes'.

**Comment by chuchana** [comment]
working of 'functions'

**Comment by eudoxia0** [comment]
Protip: http://domchristie.github.io/to-markdown/

**Comment by chuchana** [comment]
> Protip: http://domchristie.github.io/to-markdown/

Thank you. I knew should have been looking for something like that…

**Comment by chuchana** [comment]
working on "systems"

**Comment by chuchana** [comment]
working on misc

**Comment by chuchana** [comment]
working on "emacs"

**Comment by chuchana** [comment]
working on "macros"

**Comment by chuchana** [comment]
working on "process" chapter

**Comment by chuchana** [comment]
working on "windows"

**Comment by chuchana** [comment]
working on "win32"

**Comment by chuchana** [comment]
done!

**Comment by pnathan** [comment]
@chuchana - You *totally* rocked this. :yellow_heart:

**Comment by eudoxia0** [comment]
Good job team
