### ISSUE TITLE
Fix issue from the comparison of Common Lisp Testing Frameworks

### ISSUE THREAD

**Issue by phoe** [LispCookbook/cl-cookbook#382]
From the first paragraph of https://sabracrolleton.github.io/testing-framework:

> What testing framework should I use? The response should not be X or Y because it is "battle tested" or "extensible" or "has color coding". That is just content free advertising buzz words. Some of the webpages out there mentioning different common lisp unit tests frameworks merely parrot comments from library authors without validating whether they are true. **Others like the lispcookbook do silly things like advising to start with FiveAm, but then only gives examples for Prove.** The real response should be asking back - "how do you code"? But even armed with that information, how do you match a testing framework to their needs - Common Lisp has a ridiculous number of testing framework libraries.

**Comment by phoe** [comment]
Also from Reddit:

> I've been told corrections/suggestions can be submitted as issues or as pull requests against the org file at https://github.com/sabracrolleton/sabracrolleton.github.io

**Comment by pnathan** [comment]
Heh, good call out. I think we've had some churn on that page and havn't really given it a good editorial view for a while.

**Comment by sheepduke** [comment]
I would like to edit the testing page and add some content for `FiveAM` and `Mockingbird`. 
IMHO the existing content should be marked as obsolete.

**Comment by sheepduke** [comment]
Submitted #404 for it.
