### ISSUE TITLE
Review use of CLOCC

### ISSUE THREAD

**Issue by pnathan** [LispCookbook/cl-cookbook#39]
Review use of CLOCC, determine if it's appropriate, migrate to Quicklispy systems where possible and appropriate.

**Comment by eudoxia0** [comment]
It's not.

**Comment by pnathan** [comment]
What's the context here - what WAS clocc?-alexandria attempt or what?  A bit of further digging suggests Sam Steingold is still contributing to it (http://sourceforge.net/p/clocc/hg/ci/default/tree/)

**Comment by eudoxia0** [comment]
Well, it seems like an outdated collection of utilities. The last commit was January this year.

I mean, whatever it can do, other libraries can do it better. The goal of this is pretty much to keep lispers away from abandonware.

**Comment by pnathan** [comment]
I downloaded it and looked it over. Lots of nifty stuff there, afaict - but nothing that *per se* should live in the cookbook. 

Bug 39 should be reframed thusly: replace references to CLOCC with references to maintained Quicklisp'd systems.

**Comment by wobh** [comment]
I rather doubt that "avoiding abandonware" is a useful concern for CL at this point. I think it would be worth preparing forks of CLOCC instead.

**Comment by pnathan** [comment]
@wobh - it is a useful concern - if a library relies on features of, say, Genera, then it's not precisely optimal. It's also the case that it's good to be able to report bugs and have them fixed!

CLOCC has been under maintenance and development since 2000, although development has considerably fallen off. It's pretty clearly a previous generation of Common Lisp work - no quicklisp, no ASDF. 

I personally think it would be ideal to work on getting CLOCC migrated to 2015 in some sense. 

However, that doesn't mean it should be in the cookbook today - someone using the cookbook is probably going to strongly prefer Quicklisp-based libraries.
