### ISSUE TITLE
Wrong command line in scripting.md for "ros build" on SBCL without compression

### ISSUE THREAD

**Issue by leuler** [LispCookbook/cl-cookbook#390]
In "Building a self-contained executable", "With Roswell or Buildapp" it says about SBCL's core compression:

> You can disable it with `ros build --disable-compression <app.ros>`

This gives me the following error message (using roswell 21.05.14.109):

`Usage: ros build [<file>] [[options]]`

Using

`ros build <app.ros> --disable-compression`

works.

I have not tried to search whether this might be due to a recent change in roswell.

**Comment by vindarel** [comment]
thanks
