### ISSUE TITLE
Use JavaScript to generate a table of contents for each page

### ISSUE THREAD

**Issue by eudoxia0** [LispCookbook/cl-cookbook#40]
After #37 

Libraries:
- http://projects.jga.me/toc/

**Comment by vindarel** [comment]
Hi there, I tried a bit and ended up with this https://github.com/vindarel/cl-cookbook/commit/6fc8b284321bae5c5db22f637a03d23e9e134fe4 It doesn't work though, the toc is not being built. If you have any remark or will to have a look at this feature, be welcome :)

**Comment by pnathan** [comment]
:+1:
