### ISSUE TITLE
Improve contributing page to make it easier for beginners

### ISSUE THREAD

**Issue by sheepduke** [LispCookbook/cl-cookbook#403]
Hi folks, after a quite long break I came back to Lisp world. I want to write something for testing (see #382 ) now.

However, I lost the Jekyll environment and tried to setup it and finally succeeded after 2 hours effort.

I think the current contributing guide is not friendly enough for people who seldom use Ruby. I use Gentoo and Ruby 2.5 was masked for being too old, also system-wide `Jekyll` installation did not work, so I had to go for a hard way.

I think it might be improved by providing more info for non-Ruby users:
1. Clone & build `rbenv` and `ruby-build` (as a rbenv plugin) and install them to `~/.rbenv`. Or use homebrew.
2. Install the right version of `Bundler` from the `Gemfile.lock`. (The current version specified in README is wrong.)

In that case, one can easily setup a LispCookbook environment by copy-paste commands and quickly dive into the cookbook development.

What do you think?

**Comment by pnathan** [comment]
1. I would concur that the Jekyll system is a bit miserable, and more than
likely that its past time to at least update to the latest.

2. The most hacky way would be to encode the existing system in a Docker,
but the uid/gid issues presented there tend to make it a grief.

3. It'd be nice if there was a Lisp system to do this without Jekyll.
Failing that, if there's a more portable & less grievous way than Ruby
Jekyll, that'd be good. I wonder if the Go ecosystem has a Jekyll port;
that would at least get us a static binary to download, rather than
requiring a full Ruby setup (blah).

**Comment by sheepduke** [comment]
> 1. I would concur that the Jekyll system is a bit miserable, and more than
> likely that its past time to at least update to the latest.
>
1. Agreed. Having to install a software of outdated version is quite
painful.

> 2. The most hacky way would be to encode the existing system in a Docker,
> but the uid/gid issues presented there tend to make it a grief.
>
2. I agree that a docker image would be more friendly compared to the
current solution. Would you please elaborate the uid/gid issue? I recall
not every docker image would suffer from it.

> 3. It'd be nice if there was a Lisp system to do this without Jekyll.
> Failing that, if there's a more portable & less grievous way than Ruby
> Jekyll, that'd be good. I wonder if the Go ecosystem has a Jekyll port;
> that would at least get us a static binary to download, rather than
> requiring a full Ruby setup (blah).
>
3. I have tried Hugo system (written in Go) and it was rather easy to
setup. Are there any distinctive feature of Jekyll that we require? As
for the Lisp part, I think @vindarel have more knowledge to answer.

I think migrating to another blogging system is a big decision and
requires more discussion. Before that happens, adding some text to
README would be much easier...;-)

**Comment by vindarel** [comment]
> Before that happens, adding some text to README would be much easier...;-)

Absolutely :) I'll merge any content you can add to the README.

Hugo is great and fast, we must only ensure the new system keeps the actual URI layout.

> Hi folks, after a quite long break I came back to Lisp world.

I see that! Welcome back.

**Comment by sheepduke** [comment]
> Hugo is great and fast, we must only ensure the new system keeps the actual URI layout.
> 
Hugo is faster than Jekyll, and easier to setup. The Ruby/gem version hell is really annoying.

I will try to play around with Hugo and setup a demo site. I will keep you updated once I am done, then we may evaluate whether it is worthy to perform the migration.

> I see that! Welcome back.
> 
Thank you. Well, every time I got attracted by another programming language (also as hobby), I would badly miss CL's real interactive programming and flexibility. It is true that CL's ecosystem is not so large compared to more main-stream alternatives, but I have never got such power (or at least a feeling of being powerful) in other PLs.

As for the ecosystem, at least we still have many new projects coming up. I believe it will eventually getting better...

**Comment by sheepduke** [comment]
I did some investigation about Hugo. Well, it is truly faster, but it requires changing the current structure and I do not think it is worthy to migrate.

By the way has anyone ever used this? It is a blogware written in Common Lisp.
https://github.com/coleslaw-org/coleslaw

It might be interesting to display CL content in a blogware written in CL...

**Comment by sheepduke** [comment]
Done via commit `21bcde5`

**Comment by alx-a** [comment]
> By the way has anyone ever used this? It is a blogware written in Common Lisp.
https://github.com/coleslaw-org/coleslaw

I played with it a few years back but did not take to production. I suppose the key issue would be insuring that 
* The existing Cookbook URL schema can be maintained
If there's interest, we can break this down into testing steps and divide them up.

**Comment by sheepduke** [comment]
On 2021-09-07 01:44, alx-a ***@***.***> wrote:
>> By the way has anyone ever used this? It is a blogware written in Common Lisp.
> https://github.com/coleslaw-org/coleslaw
>
> I played with it a few years back but did not take to production. I suppose the key issue would be insuring that 
> * The existing Cookbook URL schema can be maintained
> If there's interest, we can break this down into testing steps and divide them up. 
>
I may not have enough time to drive this, but I should be able to take
some burdens. :-)

**Comment by alx-a** [comment]
I'm prioritizing my draft on documentation first, but I do agree that it would be proper to generate the Cookbook with CL. We should get back to this at some point, i'll ping after the draft.
