### ISSUE TITLE
"Web Development" page refers to package that no longer appears to be on Quicklisp

### ISSUE THREAD

**Issue by emacdona** [LispCookbook/cl-cookbook#421]
When I try to run this at the SBCL repl:
```
(ql:quickload '("hunchentoot" "caveman" "spinneret" "djula"))
```

I get this error:
```
  System "caveman" not found
```

It looks like the author has moved on to caveman2: https://github.com/fukamachi/caveman

And it's not clear that it's backward compatible.

I'm very new to Lisp, so I'm not sure how to confirm whether or not an artifact is still on Quicklisp. I come from the Java world, where once an artifact is published it never disappears. This is all kinda new to me :-)

**Comment by vindarel** [comment]
Thanks, you're right, the official way to install Caveman is to quickload "caveman2".

> (ql:quickload :caveman2) ;; from its github

So it looks more like a mistake on our side than a disappearing library on Quicklisp. However this can happen, Quicklisp is moderated, when a system fails to build and receives no fix in time, it is removed. We can check the available system son quickdocs.org and in `~/quicklisp/dists/quicklisp/systems.txt` and/or releases.txt… where we find "caveman" too…
