### ISSUE TITLE
Pathname recipes

### ISSUE THREAD

**Issue by contrapunctus-1** [LispCookbook/cl-cookbook#425]
I was thinking of adding recipes for some common pathname operations, but the files page says -

> In this chapter, we use mainly [namestrings](http://www.lispworks.com/documentation/HyperSpec/Body/19_aa.htm) to [specify filenames](http://www.lispworks.com/documentation/HyperSpec/Body/19_.htm). The issue of [pathnames](http://www.lispworks.com/documentation/HyperSpec/Body/19_ab.htm) needs to be covered separately.

...so I guess I'll make a new page (and thus announce it here). Although, to be honest, "Files and Directories" is actually where I expect to have path operations too...

**Comment by vindarel** [comment]
yeah, a new section on that page makes sense. Any recipe on pathnames is very welcome!
