### ISSUE TITLE
Format problems in epub version of cookbook: Can not open in emacs nov.el

### ISSUE THREAD

**Issue by johanwiden** [LispCookbook/cl-cookbook#459]
I can read the epub version of the cookbook in Okular, but not in emacs nov.el.
I wondered about that so I installed the freely available tool epubcheck (available at least in Ubuntu), https://github.com/w3c/epubcheck. It found one fatal error, and 139 non fatal errors.
FATAL(RSC-016): common-lisp-cookbook.epub/ch031.xhtml(407,10): Fatal Error while parsing file: The element type "br" must be terminated by the matching end-tag "</br>".

**Comment by johanwiden** [comment]
Perhaps this project needs a set of (automatic) tests, at least sanity checks?
One such test could be to build PDF and EPUB versions of the document and then run format checkers on them.

**Comment by johanwiden** [comment]
I believe I solved the problem: There are two empty fields in metadata.txt: "identifier" and "publisher".
If I remove these fields, and then generate the epub, then emacs nov.el can display the document.

Another, unrelated, bug: In README.md, the line
  Run gem install bundler -v `1.17.3` to install bundler.
should be
  Run gem install bundler -v `2.1.4` to install bundler.
(The version listed at the end of Gemfile.lock)

**Comment by vindarel** [comment]
Hi, thanks for the good pointers.

I fixed the missing metadata fields and reduced a little the number of non-fatal errors, but I was unable to try nov.el. Is this file good https://github.com/LispCookbook/cl-cookbook/releases/download/2022-08-30/common-lisp-cookbook.epub ?

**Comment by vindarel** [comment]
Fixed thanks to your PR.
