### ISSUE TITLE
Multidimensional array chapter's array-operations does not point to the newest link (the lisp-stat one)

### ISSUE THREAD

**Issue by Inc0n** [LispCookbook/cl-cookbook#465]
As the title suggest, also from [bendudson/array-operations](https://github.com/bendudson/array-operations):
> The array-operations library is now maintained by @Symbolics as part of the [Lisp-Stat](https://github.com/Lisp-Stat/) project. The new repository is https://github.com/Lisp-Stat/array-operations.

I think it may not be just simply update the link, as I found there are serveral more demonstration on some of the macros in the package, which points to [bendudson/array-operations](https://github.com/bendudson/array-operations).

If possible, please advise on whether it should be updated (the link), and how. And I would like to make a PR contribution if possible :)

**Comment by snunez1** [comment]
If you do update the examples, you'll probably want to take them from the [array-operations manual](https://lisp-stat.dev/docs/manuals/array-operations/).

**Comment by Inc0n** [comment]
I just had a look at the examples, it seems lisp stat's array operation does not support outer product anymore.

**Comment by snunez1** [comment]
Hmmm.  If it supported it before, it should support it now.  I didn't remove anything.  Do you have an example of the before behaviour?  It may also be that it's not documented.  Whilst it was living at Ben Dudson's repo the documentation diverged.  In fact there's still functionality I haven't documented.  The tests have complete coverage though[

**Comment by Inc0n** [comment]
Sorry, my bad. 
1. I had something going on with a readtable that messed up my testing on repl.
2. I didn't find #'outer in the documentaiton
3. Just tested it, It works

**Comment by snunez1** [comment]
Great!  Would love an example & documentation for it if you have the time.

**Comment by Inc0n** [comment]
That would be fairly reasonable task to add to my TODOs.
About cl-cookbook tho, I have updated the links pointing to the one by Lisp-stat. 
The small problem here is I couldn't get jekyll to setup with ruby (Mac M1 machine I got).
Would that be ok ... if I submit my PR ...

**Comment by snunez1** [comment]
I am not a committer to cl-cookbook.  I just monitor to see what's happening here because I find it a useful resource.  Hopefully one of the owners/committers will let you know about the need (or not) for jekyll.

**Comment by vindarel** [comment]
> Would that be ok ... if I submit my PR ...

It should be OK. The content is markdown so it's easy to review and I can check if necessary.

**Comment by vindarel** [comment]
it's done in the PR. Closing. Thanks.
