### ISSUE TITLE
Add a note about sharp sign

### ISSUE THREAD

**Issue by svetlyak40wt** [LispCookbook/cl-cookbook#469]
In the chapter https://lispcookbook.github.io/cl-cookbook/functions.html#referencing-functions-by-name-single-quote--or-sharpsign-quote- book says:

```
Using function or the #' shorthand allows us to refer to local functions. If we pass instead a symbol to funcall, what is called is always the function named by that symbol in the global environment.
```

Probably it will be useful to add that sharpsign catches the function by value, and when it is redefined in future, the previously watched thunks will keep executing old code:

```lisp
CL-USER> (defun foo ()
           :foo-result)
FOO
CL-USER> (defparameter *thunk* #'foo)
*THUNK*
CL-USER> (funcall *thunk*)
:FOO-RESULT

;; Now let's redefine it:
CL-USER> (defun foo ()
           :blah)
FOO
CL-USER> (funcall *thunk*)
:FOO-RESULT
```

Whereas with 'foo redefinition works as expected, because funcall resolves function in runtime:

```lisp
CL-USER> (defun foo ()
           :foo-result)
FOO
CL-USER> (defparameter *thunk* 'foo)
*THUNK*
CL-USER> (funcall *thunk*)
:FOO-RESULT

;; Now let's redefine it:
CL-USER> (defun foo ()
           :blah)
WARNING: redefining COMMON-LISP-USER::FOO in DEFUN
FOO
CL-USER> (funcall *thunk*)
:BLAH
```

This may be a desired or not desired behaviour. But definitely it might surprise a novice.

**Comment by vindarel** [comment]
The example with `flet` aimed to explain this idea, but your example and your wording is good and complementary.

**Comment by svetlyak40wt** [comment]
Great. Thank you for adding this content!
