### ISSUE TITLE
Feature Request: Better Instructions on uiop:command-line-arguments

### ISSUE THREAD

**Issue by jgarte** [LispCookbook/cl-cookbook#477]
## Proposal

I think we should have better instructions on using `uiop:command-line-arguments` and with more context.

### References For Improving the Documentation on uiop:command-line-arguments

https://lispcookbook.github.io/cl-cookbook/scripting.html#parsing-command-line-arguments

https://quickref.common-lisp.net/uiop.html#index-command_002dline_002darguments

https://github.com/search?q=uiop%3Acommand-line-arguments+language%3Alisp&type=code

https://github.com/charJe/triads/blob/master/src/command-line.lisp#L23

**Comment by vindarel** [comment]
Also: rewrite the options parsing example from `unix-opts` to `clingon`, much more complete.

https://github.com/dnaeon/clingon
