### ISSUE TITLE
Bad formatting in the "Evaluation context" subsection of macros.md.

### ISSUE THREAD

**Issue by ZSHZ0000** [LispCookbook/cl-cookbook#484]
The erroneous markdown renders improperly in browsers, PDF compilation & possibly the EPUB book, the rendering is as follows:

```
_If we call it thus ..._     |_The parameters' values are ..._
-----------------------------|-----------------------------------
`(foo a)`                    | `x=a`, `y=nil`, `cxt=null`
`(foo (+ a 1) (- y 1))`      |`x=(+ a 1)`, `y=(- y 1)`, `cxt=null`
`(foo a b :cxt (zap zip))`   |`x=a`, `y=b`, `cxt=(zap zip)`
```

which looks wrong & erroneous, maybe this was the intended result?

| _If we call it thus ..._   | _The parameters' values are ..._     |
|----------------------------|--------------------------------------|
| `(foo a)`                  | `x=a`, `y=nil`, `ctx=null`           |
| `(foo (+ a 1) (- y 1))`    | `x=(+ a 1)`, `y=(- y 1)`, `ctx=null` |
| `(foo a b :ctx (zap zip))` | `x=a`, `y=b`, `ctx=(zap zip)`        |

**Comment by vindarel** [comment]
Thanks!
