### ISSUE TITLE
Change "Threads" page name to "Concurrency and parallelism"

### ISSUE THREAD

**Issue by tsilvap** [LispCookbook/cl-cookbook#501]
At least for me, the name "Threads" makes it seem like the page only talks about thread-based, preemptive multitasking recipes.

But in reality, the page goes over the [lparallel](https://lparallel.org/) library, which supports many other models of multitasking. So I think a name such as "Concurrency and parallelism" is more appropriate for the page.

**Comment by vindarel** [comment]
Indeed!
