### ISSUE TITLE
Actually Show An Example Of The Interpol Syntactic Sugar

### ISSUE THREAD

**Issue by jgarte** [LispCookbook/cl-cookbook#511]
This is a ticket to create an example with the interpol syntax mentioned in this section:

https://lispcookbook.github.io/cl-cookbook/regexp.html#syntactic-sugar

**Comment by vindarel** [comment]
For once, I think we should remove content. cl-interpol might be cool but it doesn't bring a missing feature, and it requires some setup. And I don't like much dealing with readtables, from experience I find it a bit clunky.

**Comment by jgarte** [comment]
I can get behind that.

**Comment by vindarel** [comment]
Done. Was quick.
