### ISSUE TITLE
where does "slime-setup" code from editors.md go in .emacs?

### ISSUE THREAD

**Issue by may** [LispCookbook/cl-cookbook#522]
Hi! Thank you so much for all your work on the Lisp Cookbook, it's super helpful.

I was trying to get setup with SLIME again today and saw the very helpful line in your editors.md file that reads:

`(slime-setup '(slime-fancy slime-quicklisp slime-asdf))`

It looks like it would be really helpful, but my Emacs barfs on it when I add it into `.emacs`, and I was not able to determine, from reading the docs, if I needed to wait to execute it until after `slime` had been loaded, or something else?  It didn't appear to do anything when I executed it in *scratch* after running `M-x slime`.

I'm not asking for tech support, and this is by no means urgent, I just thought there might be value in the feedback that that part of the setup was unclear. 

Thanks!

**Comment by vindarel** [comment]
> thank you

me and the 74 contributors appreciate ; )

Does `(require 'slime)` help?

**Comment by may** [comment]
So, it appears to be working! Thank you!

When I evaluate slime-contribs in a scratch buffer:
`(slime-fancy slime-quicklisp slime-asdf)`

However, two items of note:
First, concerningly,  this no longer works:

`M-x package-install RET slime RET`

the closest I get when running on an Ubuntu 22.04-based distro with Emacs 27.1 is slime-volleyball which we obviously don't want.
 
Presumably users could add MELPA or similar to get 'real' SLIME, but this could be another stumbling block for new users.

It looks like instruction to use MELPA instead is already included ony our Emacs as an IDE page.

Putting myself in the shoes of a new user, I instead followed the steps here: https://lisp-lang.org/learn/getting-started/
 
 and ended up with the following `.emacs` when all was said and done:
 
 ```
(load (expand-file-name "~/.quicklisp/slime-helper.el"))
(setq inferior-lisp-program "sbcl")

(require 'slime)
(slime-setup '(slime-fancy slime-quicklisp slime-asdf))
```

Which, as mentioned above, is working!

Minus, second, a small warning on startup that may trip up new users (might be worth mentioning in the guide, but not critical):

![image](https://github.com/LispCookbook/cl-cookbook/assets/82888/8b4415c7-2a83-443e-b98f-09d41649b839)

Thanks for the quick and correct response!

**Comment by vindarel** [comment]
Thanks for your addition, it's super valuable that newcomers improve the getting started guides. 

On Mint 20: `apt search slime` gives me `slime` and `slimevolley`.

**Comment by may** [comment]
Absolutely. It's great to be able to contribute, and great to be appreciated.

So I agree; it's totally in the *default* *distro* package repos. Here's POP_OS 22.04, based on Ubuntu 22.04.

![image](https://github.com/LispCookbook/cl-cookbook/assets/82888/00b5a3ee-e1cc-4ef8-990c-eeb62c2c8115)

I guess I was confused because I assumed `M-x package-install slime` would work out of the box, and it doesn't; it's not in ELPA, but it is in MELPA.

I've written up some enhanced instructions for those new to emacs, take a look and merge/reject as you see fit, thanks!
