### ISSUE TITLE
Fix typos, grammar, etc

### ISSUE THREAD

**Issue by cgay** [LispCookbook/cl-cookbook#540]
Hi, is it okay if I fix typos and similar minutiae as I read through the cookbook, and file the resulting PRs against this bug?

**Comment by vindarel** [comment]
Ab-so-lu-te-ly, thank you in advance. I might ping you in future PRs too ; )

**Comment by cgay** [comment]
Cool. Not saying I'll go through the whole thing at once or anything though. :)

BTW / FYI, I was unable to get jekyll running on macOS 14 (Sonoma) due to Ruby gem dependency problems. (I followed the jekyll instructions to install Ruby because the system's Ruby isn't trusted for some reason.) Jekyll doesn't claim to support Sonoma yet....   So I can't test my changes very well...but they'll be simple changes.

**Comment by vindarel** [comment]
Ok, no pb for Jekyll we have a slightly outdated stack. You could also enable Github pages of your fork and check the result there, but as you said there's probably no need to check simple changes.

Oh, did you set up OpenDylan's website? The docs are pleasant to read and the theme is stellar (Sphinx, I see).

**Comment by cgay** [comment]
> Ok, no pb for Jekyll we have a slightly outdated stack. You could also enable Github pages of your fork and check the result there, but as you said there's probably no need to check simple changes.

Ah, that sounds like a good solution. I'll give it a try. Or I might try one of the other methods to get Jekyll running on my machine....

> Oh, did you set up OpenDylan's website? The docs are pleasant to read and the theme is stellar (Sphinx, I see).

I did. I'm quite happy with Sphinx.

One of the ideas kicking around in my head is to try and make it easy to provide better docs for CL projects. Sphinx, with a custom CL domain, would be one way to do that. The docs could have cross references to other CL projects' docs, a multi-project search index, etc.  Sphinx would work, but wouldn't it be cool if we could do it all in Common Lisp?

**Comment by vindarel** [comment]
> with a custom CL domain

did you see https://github.com/russell/sphinxcontrib-cldomain/ ? It works©, I set it up for an unpublished project.

(it wouldn't work for the Cookbook, for which it would be cool to do it all in CL indeed)

> a multi-project search index, etc

that's interesting (reminds me of Ultralisp's symbol search).

**Comment by cgay** [comment]
> > with a custom CL domain
> 
> did you see https://github.com/russell/sphinxcontrib-cldomain/ ? It works©, I set it up for an unpublished project.

Thanks, I'll make a note of it.

> (it wouldn't work for the Cookbook, for which it would be cool to do it all in CL indeed)

Why wouldn't it work for the CL Cookbook?

> > a multi-project search index, etc
> 
> that's interesting (reminds me of Ultralisp's symbol search).

Yep, I just discovered that yesterday.  If I'm totally honest it seems like a mismatch for what Ultralisp is, since it [doesn't provide a way to search for systems themselves](https://github.com/ultralisp/ultralisp/issues/233).  But that's a separate issue....

**Comment by vindarel** [comment]
> Why wouldn't it work for the CL Cookbook?

I mean it could (according we respect the existing URLs), but it wouldn't be the best IMO. Transforming .md files to .rst, imposing rst to contributors… I'd prefer a fast and simple to install solution (à la Hugo), and using a CL site generator would be nice.
