### ISSUE TITLE
continuous deply to gh-pages

### ISSUE THREAD

**Issue by pnathan** [LispCookbook/cl-cookbook#57]
The `master` branch of the cl-cookbook should have a CD to gh-pages  so no manual deploys are needed.

**Comment by pnathan** [comment]
I can put time in on this, this week. It should be really simple. But if someone wants to do this, go for it ahead of me.

**Comment by chuchana** [comment]
Wouldn't it make sense to move everything to the gh-pages branch and [delete the master branch](http://stackoverflow.com/questions/17396509/how-can-i-only-have-a-gh-pages-branch)?

**Comment by pnathan** [comment]
@chuchana Not sure, honestly. It would certainly surprise contributors who aren't very git-skilled. On the other hand, it would make more technical sense.

**Comment by chuchana** [comment]
@pnathan I just went back to look at the links I posted [here](https://github.com/LispCookbook/cl-cookbook/pull/46) and edited my comment. It looks to me like any other solution is more complicated.

**Comment by pnathan** [comment]
Hmmm. Yes. although, if a ci solution could do "git merge gh-pages && git push", that'd be nice too. I wonder....

**Comment by vindarel** [comment]
Hello ! Did you try something here ? Will you ? An opinion of the best approach ?

**Comment by pnathan** [comment]
Hm, it doesn't seem to auto deploy, does it?

I'm on a plane tomorrow all day, but I may get some layover time to take a
look.

If, however, you believe you can move faster, please feel free to do so.

**Comment by vindarel** [comment]
No, it doesn't auto-deploy :) (waiting for changes on https://lispcookbook.github.io/cl-cookbook/os.html after last PR)

> If, however, you believe you can move faster, please feel free to do so.

mmh I don't think so with github (learned gitlab pages instead).

**Comment by pnathan** [comment]
Shifted github to use `master` as the deployment branch.

/cc @vindarel

**Comment by vindarel** [comment]
Great !!

Now with auto deploy, syntax highlighting, a TOC soon, we can advertise a bit and add content like crazy. btw do you know if anybody contacted the cl-cookbook on sourceforge ? Is it time to ask them to link to here ?

ps: just saw a typo of mine… `uiop` instead of `uiop` :(

**Comment by pnathan** [comment]
I wrote a note to the maintainer listed on sourceforge. He lives across the
globe from me, so he may not respond for some time.

The next big thing should probably be an improved landing page. The 1994
style list of links without any style is a little painful to scroll through
efficiently IMO.

**Comment by vindarel** [comment]
Indeed. I remember Eudoxia wanting to take care of the CSS: https://github.com/LispCookbook/cl-cookbook/issues/36
