### ISSUE TITLE
Switch * to CL-USER> in code examples

### ISSUE THREAD

**Issue by otjura** [LispCookbook/cl-cookbook#60]
I think the * is a bit difficult to separate from code because it means multiplication, especially to newbies. SLIME which is favoured by pretty much everyone 2015AD for lisping has CL-USER> prompt on REPL and there is no way that gets mixed.

**Comment by otjura** [comment]
Oh and if you guys greenlight this imma sed things up again and make another megacommit :smile:

**Comment by pnathan** [comment]
Send in the PR. I noticed some `>` and some `CL-USER>`.

**Comment by otjura** [comment]
Pull request is there. It's a bit partial, didn't go through all of the files yet.
