### ISSUE TITLE
"Defining Systems" page not mentioning ASDF ?

### ISSUE THREAD

**Issue by vindarel** [LispCookbook/cl-cookbook#91]
https://lispcookbook.github.io/cl-cookbook/systems.html

seems like a miss :S 

ASDF3 tutorial/best practices: https://gitlab.common-lisp.net/asdf/asdf/blob/master/doc/best_practices.md

**Comment by pnathan** [comment]
```
(eval-when (:load-toplevel :execute)
  (shadow 'cl:require))
```

I'm just going to go out here and say, "yeah this is zombie advice"
