### ISSUE TITLE
Testing: should mention newer test frameworks

### ISSUE THREAD

**Issue by vindarel** [LispCookbook/cl-cookbook#92]
such as Prove, according to http://eudoxia.me/article/common-lisp-sotu-2015#testing

Furthermore where is RT's doc ? Old and messy links on the given http://www.cliki.net/RT

**Comment by pnathan** [comment]
This might be a good place to carefully do a rewrite. state of the art in testing in the industry has come pretty far since the cookbook started.

**Comment by vindarel** [comment]
Shall I delete this page and… well, copy Prove's tutorial, or only link to it ? (preferably to not duplicate content, but it will do a rather empty page).

**Comment by pnathan** [comment]
I'd probably have an empty page and some copypaste of snippets. 

I use fiveAM myself.
